GET http://localhost:8000/students

###

GET http://localhost:8000/students/

###

POST http://localhost:8000/students
Content-Type: application/json

  {
    "name": " add the name here",
    "class": "add the class name here"
  }




